# Generated by Django 4.2.17 on 2024-12-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_entry_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.CreateModel(
            name='BoomSig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entryboom', models.CharField(default='N', max_length=1)),
                ('entrysynctime', models.DateTimeField(auto_now=True)),
                ('exitboom', models.CharField(default='N', max_length=1)),
                ('exitsynctime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'boomsig',
            },
        ),
    ]
