# Generated by Django 4.2.17 on 2024-12-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boom_endpoints', '0001_initial_migrations_for_controlling_boom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boomsig',
            name='entrysynctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boomsig',
            name='exitsynctime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
